import type { CraftJob, GameState, RecipeDef, RecipeId, ResourceId } from '../model/types';
import { BreakdownBuilder, type Breakdown } from '../core/breakdown';
import { clamp } from '../core/math';
import { RECIPES, RECIPE_BY_ID } from '../data/recipes';
import { ITEM_BY_ID } from '../data/items';
import { FACILITY_BY_ID } from '../data/facilities';
import { findFacility, isOperational, staffOf, staffPower } from './facilities';
import { addItem, itemCount, removeItem } from './inventory';
import { canAfford, payCost } from './facilities';
import * as T from './traits';

/**
 * Crafting.
 *
 * Recipes consume resources at queue time (so the player cannot queue ten things they
 * cannot afford) and then accumulate *labour* generated by the staff of the recipe's
 * facility. A skilled engineer finishes a welding rig in a day where an untrained survivor
 * takes three, which is what makes staffing the Workshop a decision rather than a chore.
 */

export interface RecipeAvailability {
  recipe: RecipeDef;
  ok: boolean;
  reason?: string;
  /**
   * True when the only thing standing in the way is an unfinished research project.
   *
   * The workshop's "hide un-researched" filter needs to know this, and matching on the
   * reason string would have made that filter break the moment the reason was translated.
   */
  researchLocked?: boolean;
  /** Estimated days at the current staffing level. */
  estimatedDays: number | null;
}

export function recipeAvailability(state: GameState, recipe: RecipeDef): RecipeAvailability {
  const facility = findFacility(state, recipe.facility);
  const facilityName = FACILITY_BY_ID[recipe.facility]?.name ?? recipe.facility;

  if (recipe.requiresResearch && !state.research.completed.includes(recipe.requiresResearch)) {
    return { recipe, ok: false, reason: 'Requires research', researchLocked: true, estimatedDays: null };
  }
  if (!facility || facility.status === 'building') {
    return { recipe, ok: false, reason: `Requires ${facilityName}`, estimatedDays: null };
  }
  if (facility.level < recipe.minLevel) {
    return { recipe, ok: false, reason: `Requires ${facilityName} level ${recipe.minLevel}`, estimatedDays: null };
  }
  if (!isOperational(facility)) {
    return { recipe, ok: false, reason: `${facilityName} is offline`, estimatedDays: null };
  }
  const affordability = canAfford(state.resources, recipe.cost);
  if (!affordability.ok) {
    const first = affordability.missing[0]!;
    return {
      recipe,
      ok: false,
      reason: `Needs ${Math.ceil(first.needed)} ${first.resource}`,
      estimatedDays: null,
    };
  }
  for (const entry of recipe.itemCost ?? []) {
    if (itemCount(state, entry.itemId) < entry.count) {
      return {
        recipe,
        ok: false,
        reason: `Needs ${entry.count}× ${ITEM_BY_ID[entry.itemId]?.name ?? entry.itemId}`,
        estimatedDays: null,
      };
    }
  }

  const rate = craftingRate(state, recipe).total;
  return {
    recipe,
    ok: true,
    estimatedDays: rate > 0 ? Math.max(1, Math.ceil(recipe.labour / rate)) : null,
  };
}

/** Labour per day available to a recipe's facility, with every term labelled. */
export function craftingRate(state: GameState, recipe: RecipeDef): Breakdown {
  const b = new BreakdownBuilder();
  const facility = findFacility(state, recipe.facility);
  if (!facility || !isOperational(facility)) {
    b.base('No operational facility', 0);
    return b.build({ min: 0 });
  }
  const def = FACILITY_BY_ID[recipe.facility]!;
  const staff = staffOf(state, facility);
  if (staff.length === 0) {
    b.base('Unstaffed', 0);
    b.note(`Nobody is working in the ${def.name}.`, undefined, `Assign a survivor to the ${def.name}.`);
    return b.build({ min: 0 });
  }
  b.base(`${def.name} crew`, staffPower(state, facility) * 8, `${staff.length} assigned.`);
  if (facility.defId === 'workshop' && facility.level >= 3) b.mul('Level 3 tooling', 2.0);
  return b.build({ min: 0, round: 1 });
}

export function queueCraft(state: GameState, recipeId: RecipeId): { ok: boolean; reason?: string } {
  const recipe = RECIPE_BY_ID[recipeId];
  if (!recipe) return { ok: false, reason: 'Unknown recipe' };
  if (state.craftQueue.length >= 6) return { ok: false, reason: 'The queue is full' };
  const availability = recipeAvailability(state, recipe);
  if (!availability.ok) return { ok: false, reason: availability.reason };

  // The Tinkerer trait can waive the material cost entirely.
  const facility = findFacility(state, recipe.facility);
  const staff = facility ? staffOf(state, facility) : [];
  let freeChance = 0;
  for (const survivor of staff) freeChance = 1 - (1 - freeChance) * (1 - T.craftFreeChance(survivor));
  const roll = (state.idCounter * 2654435761) % 1000 / 1000;
  const free = freeChance > 0 && roll < freeChance;

  if (!free) {
    payCost(state.resources, recipe.cost);
    for (const entry of recipe.itemCost ?? []) removeItem(state, entry.itemId, entry.count);
  }

  state.idCounter += 1;
  state.craftQueue.push({
    id: `craft${state.idCounter}`,
    recipeId,
    progress: 0,
    required: recipe.labour,
    startedDay: state.day,
  });
  return { ok: true, ...(free ? { reason: 'Improvised from scrap — no materials used.' } : {}) };
}

export function cancelCraft(state: GameState, jobId: string): boolean {
  const index = state.craftQueue.findIndex((j) => j.id === jobId);
  if (index < 0) return false;
  const job = state.craftQueue[index]!;
  const recipe = RECIPE_BY_ID[job.recipeId];
  if (recipe) {
    // Refund the unconsumed share of the materials.
    const refund = 1 - job.progress / Math.max(1, job.required);
    for (const [resource, amount] of Object.entries(recipe.cost) as [ResourceId, number][]) {
      state.resources[resource] += Math.floor(amount * refund * 0.75);
    }
  }
  state.craftQueue.splice(index, 1);
  return true;
}

/** Advance the queue by one day. Returns log notes for completed jobs. */
export function progressCrafting(state: GameState): string[] {
  const notes: string[] = [];
  const rateCache = new Map<string, number>();
  const remaining = new Map<string, number>();

  for (const job of state.craftQueue.slice()) {
    const recipe = RECIPE_BY_ID[job.recipeId];
    if (!recipe) continue;
    if (!rateCache.has(recipe.facility)) {
      const rate = craftingRate(state, recipe).total;
      rateCache.set(recipe.facility, rate);
      remaining.set(recipe.facility, rate);
    }
    const available = remaining.get(recipe.facility) ?? 0;
    if (available <= 0) continue;
    const need = job.required - job.progress;
    const spend = Math.min(available, need);
    job.progress += spend;
    remaining.set(recipe.facility, available - spend);

    if (job.progress >= job.required) {
      addItem(state, recipe.itemId, recipe.yield);
      state.stats.itemsCrafted += recipe.yield;
      notes.push(
        `${ITEM_BY_ID[recipe.itemId]?.name ?? recipe.itemId}${recipe.yield > 1 ? ` ×${recipe.yield}` : ''} finished.`,
      );
      state.craftQueue = state.craftQueue.filter((j) => j.id !== job.id);
    }
  }
  return notes;
}

export function availableRecipes(state: GameState): RecipeAvailability[] {
  return RECIPES.map((recipe) => recipeAvailability(state, recipe));
}

/** Recipes the player could plausibly reach, for the encyclopedia. */
export function knownRecipes(state: GameState): RecipeDef[] {
  return RECIPES.filter(
    (recipe) => !recipe.requiresResearch || state.research.completed.includes(recipe.requiresResearch),
  );
}

export function craftProgressPercent(job: CraftJob): number {
  return clamp((job.progress / Math.max(1, job.required)) * 100, 0, 100);
}
